language: node_js
sudo: false
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - npm run test:lint
  - npm run test:verbose
  - npm run report:coverage
