# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v8
      - node-v10

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      - run: npm run test:lint
      - run: npm run test:junit:coverage
      - run: npm run report:coverage

      # Test results
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  node-v8:
    <<: *node-base
    docker:
      - image: node:8
  node-v10:
    <<: *node-base
    docker:
      - image: node:10

